### ISSUE TITLE
Feature Request: Copy link to Post directly to Clipboard

### ISSUE THREAD

**Issue by jamilnyc** [javenlalla/my-reddit-archiver#1]
On the Archive listing page or the post detail page, it would be great to have a button to copy the Reddit link directly to clipboard. This would make it easier to share links with other people.

**Comment by javenlalla** [comment]
Hi @jamilnyc! Thank you for the feature request. This has been added and will be included in the next released build.

On the footer of each Post on the Archive listings page and on the footer within a detail page view, there is now a `Copy` button that copies the link of the Reddit URL for the content in question upon clicking.

Usage example:
<img width="1053" alt="listing_copy_cta" src="https://github.com/javenlalla/my-reddit-archiver/assets/5437364/093c7b85-0373-4f80-9a71-6fce0b9e3dfe">
